'use client'

/**
 * Quick Export Bar Component
 * Provides one-click export buttons for common formats
 * Iteration 8: Feature Improvements
 */

import { useState, useCallback } from 'react'
import { motion } from 'framer-motion'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import {
  Download,
  FileJs,
  FileText,
  FileMd,
  Code,
  Copy,
  Check,
  Files,
} from '@phosphor-icons/react'
import { toast } from 'sonner'

interface QuickExportBarProps {
  description?: string
  title?: string
  timestamps?: string
  hashtags?: string[]
  faq?: string
  productName?: string
  platform?: string
  className?: string
}

export function QuickExportBar({
  description,
  title,
  timestamps,
  hashtags = [],
  faq,
  productName = 'Content',
  platform = 'youtube',
  className,
}: QuickExportBarProps) {
  const [exporting, setExporting] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  // Generate content for export
  const generateTextContent = useCallback(() => {
    const sections = [
      title && `# 타이틀\n${title}`,
      description && `# 설명\n${description}`,
      timestamps && `# 타임스탬프\n${timestamps}`,
      hashtags.length > 0 && `# 해시태그\n${hashtags.join(' ')}`,
      faq && `# FAQ\n${faq}`,
    ].filter(Boolean)

    return sections.join('\n\n---\n\n')
  }, [title, description, timestamps, hashtags, faq])

  const generateJsonContent = useCallback(() => {
    return JSON.stringify({
      productName,
      platform,
      generatedAt: new Date().toISOString(),
      content: {
        title,
        description,
        timestamps,
        hashtags,
        faq,
      },
    }, null, 2)
  }, [productName, platform, title, description, timestamps, hashtags, faq])

  const generateMarkdownContent = useCallback(() => {
    const md = []
    md.push(`# ${productName}\n`)
    md.push(`> Generated for ${platform} on ${new Date().toLocaleDateString('ko-KR')}\n`)

    if (title) {
      md.push(`## 타이틀\n\n${title}\n`)
    }

    if (description) {
      md.push(`## 설명\n\n${description}\n`)
    }

    if (timestamps) {
      md.push(`## 타임스탬프\n\n\`\`\`\n${timestamps}\n\`\`\`\n`)
    }

    if (hashtags.length > 0) {
      md.push(`## 해시태그\n\n${hashtags.join(' ')}\n`)
    }

    if (faq) {
      md.push(`## FAQ\n\n${faq}\n`)
    }

    md.push(`---\n*Generated by Samsung GEO Tool*`)

    return md.join('\n')
  }, [productName, platform, title, description, timestamps, hashtags, faq])

  // Export handlers
  const handleDownload = useCallback((content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [])

  const handleExport = useCallback(async (format: 'txt' | 'json' | 'md') => {
    setExporting(format)

    try {
      const safeProductName = productName.replace(/[^a-zA-Z0-9가-힣]/g, '_').substring(0, 30)
      const timestamp = new Date().toISOString().split('T')[0]

      switch (format) {
        case 'txt':
          handleDownload(
            generateTextContent(),
            `${safeProductName}_${timestamp}.txt`,
            'text/plain'
          )
          break
        case 'json':
          handleDownload(
            generateJsonContent(),
            `${safeProductName}_${timestamp}.json`,
            'application/json'
          )
          break
        case 'md':
          handleDownload(
            generateMarkdownContent(),
            `${safeProductName}_${timestamp}.md`,
            'text/markdown'
          )
          break
      }

      toast.success(`${format.toUpperCase()} 파일 다운로드 완료`)
    } catch (error) {
      toast.error('다운로드 실패')
    } finally {
      setExporting(null)
    }
  }, [productName, generateTextContent, generateJsonContent, generateMarkdownContent, handleDownload])

  const handleCopyAll = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(generateTextContent())
      setCopied(true)
      toast.success('전체 콘텐츠 복사됨')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast.error('복사 실패')
    }
  }, [generateTextContent])

  // Check if there's content to export
  const hasContent = description || title || timestamps || hashtags.length > 0 || faq
  if (!hasContent) return null

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn(
        'flex items-center gap-2 p-3 rounded-lg bg-muted/50 border',
        className
      )}
    >
      <span className="text-sm font-medium text-muted-foreground mr-2">
        내보내기:
      </span>

      <TooltipProvider>
        {/* Copy All */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyAll}
              className="gap-1.5"
            >
              {copied ? (
                <Check className="h-4 w-4" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              <span className="hidden sm:inline">복사</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>전체 콘텐츠 클립보드에 복사</TooltipContent>
        </Tooltip>

        {/* TXT */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleExport('txt')}
              disabled={exporting === 'txt'}
              className="gap-1.5"
            >
              <FileText className="h-4 w-4" />
              <span className="hidden sm:inline">TXT</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>텍스트 파일로 다운로드</TooltipContent>
        </Tooltip>

        {/* JSON */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleExport('json')}
              disabled={exporting === 'json'}
              className="gap-1.5"
            >
              <FileJs className="h-4 w-4" />
              <span className="hidden sm:inline">JSON</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>JSON 파일로 다운로드 (CMS용)</TooltipContent>
        </Tooltip>

        {/* Markdown */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleExport('md')}
              disabled={exporting === 'md'}
              className="gap-1.5"
            >
              <FileMd className="h-4 w-4" />
              <span className="hidden sm:inline">MD</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>Markdown 파일로 다운로드</TooltipContent>
        </Tooltip>
      </TooltipProvider>
    </motion.div>
  )
}

export default QuickExportBar
